### PR TITLE
Optimize mining threading

### PR DESCRIPTION
**Pull request by sorpaas**
Now it uses significantly less resources for building blocks, as it's only built once for all threads.

### CODE REVIEW

**Comment by sgaragagghu** [comment]
Hashrate is almost the same on my computer :slight_frown:

**Comment by 9-** [comment]
Running with ryzen 9 3900x. Got 8000ish hashrate. 
It's 15000 on monerobenchmark for 3900X.

**Comment by Sepkuh** [comment]
@9-  What are your OC settings?  How many threads?

**Comment by 9-** [comment]
> @9- What are your OC settings? How many threads?

23 threads and not overclocked.

i tried 12 threads too. It got 6000 H/s

**Pull request merged**
